// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef DeformableModelApplicationGUI_h
#define DeformableModelApplicationGUI_h
#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_Help_Dialog.H>
#include <FL/Fl_Double_Window.H>
#include "DeformableModelApplicationBase.h"
#include <FL/Fl_Menu_Bar.H>
#include "vtkFlRenderWindowInteractor.h"
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Text_Display.H>

class DeformableModelApplicationGUI : public DeformableModelApplicationBase {
public:
  DeformableModelApplicationGUI();
  Fl_Double_Window *mainWindow;
  static Fl_Menu_Item menu_[];
private:
  void cb_Load_i(Fl_Menu_*, void*);
  static void cb_Load(Fl_Menu_*, void*);
  void cb_Load1_i(Fl_Menu_*, void*);
  static void cb_Load1(Fl_Menu_*, void*);
  void cb_Load2_i(Fl_Menu_*, void*);
  static void cb_Load2(Fl_Menu_*, void*);
  void cb_Load3_i(Fl_Menu_*, void*);
  static void cb_Load3(Fl_Menu_*, void*);
  void cb_Preprocess_i(Fl_Menu_*, void*);
  static void cb_Preprocess(Fl_Menu_*, void*);
  void cb_Save_i(Fl_Menu_*, void*);
  static void cb_Save(Fl_Menu_*, void*);
  void cb_Save1_i(Fl_Menu_*, void*);
  static void cb_Save1(Fl_Menu_*, void*);
  void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
  void cb_Deform_i(Fl_Menu_*, void*);
  static void cb_Deform(Fl_Menu_*, void*);
  void cb_Show_i(Fl_Menu_*, void*);
  static void cb_Show(Fl_Menu_*, void*);
  void cb_How_i(Fl_Menu_*, void*);
  static void cb_How(Fl_Menu_*, void*);
  void cb_About_i(Fl_Menu_*, void*);
  static void cb_About(Fl_Menu_*, void*);
public:
  vtkFlRenderWindowInteractor *axialView;
  Fl_Value_Slider *axialViewSlider;
private:
  void cb_axialViewSlider_i(Fl_Value_Slider*, void*);
  static void cb_axialViewSlider(Fl_Value_Slider*, void*);
public:
  vtkFlRenderWindowInteractor *coronalView;
  Fl_Value_Slider *coronalViewSlider;
private:
  void cb_coronalViewSlider_i(Fl_Value_Slider*, void*);
  static void cb_coronalViewSlider(Fl_Value_Slider*, void*);
public:
  vtkFlRenderWindowInteractor *sagittalView;
  Fl_Value_Slider *sagittalViewSlider;
private:
  void cb_sagittalViewSlider_i(Fl_Value_Slider*, void*);
  static void cb_sagittalViewSlider(Fl_Value_Slider*, void*);
public:
  vtkFlRenderWindowInteractor *surfaceView;
  Fl_Double_Window *m_AboutWindow;
private:
  void cb_m_AboutWindow_i(Fl_Double_Window*, void*);
  static void cb_m_AboutWindow(Fl_Double_Window*, void*);
public:
  Fl_Text_Display *m_TextDisplay;
  virtual ~DeformableModelApplicationGUI();
  virtual void Help();
private:
  Fl_Text_Buffer m_TextBuffer;
public:
  virtual void Quit();
  virtual void SaveMask();
  virtual void SaveMesh();
  virtual void DeformMesh();
  virtual void LoadMesh();
  virtual void CreateMesh();
  virtual void Load();
  virtual void Show();
  virtual void Hide();
  virtual void SelectAxialSlice( int );
  virtual void SelectCoronalSlice( int );
  virtual void SelectSagittalSlice( int );
  virtual void ComputeInternalForces();
  virtual void LoadPreprocessed();
  virtual void ToggleImage();
  virtual void LoadCoefficients();
};
#endif
